### ISSUE TITLE
[7.0.100-rc.2.22452.3] Blazor server apps, pass dynamic variable to a component doesn't build on .net7

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/razor-compiler#345]
**Application Name** : Internal Tool
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number**: dotnet-sdk-7.0.100-rc.2.22452.3

DevDiv Bug Checking at ：HTTPs://devdiv.visualstudio.com/DevDiv/_workitems/edit/1611720

 
**Verify Scenarios**:
1). Windows10 RS5 x64+dotnet-sdk-7.0.100-rc.2.22452.3: Fail
2). Windows10 RS5 x64+dotnet-sdk-7.0.100-rc.1.22415.4: Fail
3). Windows10 RS5 x64+dotnet-sdk-6.0.400: Pass

**Description:**
Project doesn't build with .net7 SDK when we pass dynamic parameter to a component. This affected our internal tool build with Blazor Server , it also affects Radzen Blazor demo app, can be found here : [GitHub - radzenhq/radzen-blazor: The home of the Radzen Blazor components.](https://github.com/radzenhq/radzen-blazor/tree/master/RadzenBlazorDemos)

RadzenNumericRangeValidator component has this issue, if a Blazor Server project is using RadzenNumericRangeValidator, it doesn't build with .net7 SDK

**Minimal Repro steps**:

  1) Create a Blazor Server App
  2) In SurveyPrompt component, add a new dynamic parameter :

```
    <strong>@Title</strong>
    <strong>@TestDynamic</strong>
    [Parameter]
    public dynamic TestDynamic { get; set; }

```
 3) In Index.razor, pass TestDynamic to SurveyPrompt component
```
<SurveyPrompt TestDynamic="4" Title="How is Blazor working for you?" />

```
4) Build the application

**Expected Result using 6.0.400 SDK**
Build succeeded.

**Actual Result using 7.0.100-rc.2.22452.3**

```
C:\Users\v-altunc\source\repos\BlazorApp3\BlazorApp3\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.S
ourceGenerators.RazorSourceGenerator\Pages_Index_razor.g.cs(97,144): error CS0400: The type or namespace name 'dynamic'
 could not be found in the global namespace (are you missing an assembly reference?) [C:\Users\v-altunc\source\repos\Bl
azorApp3\BlazorApp3\BlazorApp3.csproj]
C:\Users\v-altunc\source\repos\BlazorApp3\BlazorApp3\Pages\Index.razor(9,28): error CS1503: Argument 1: cannot convert
from 'int' to 'dynamic' [C:\Users\v-altunc\source\repos\BlazorApp3\BlazorApp3\BlazorApp3.csproj]

```
@dotnet-actwx-bot @dotnet/compat

**Comment by mkArtakMSFT** [comment]
@jaredpar this seems to be a regression in 7.0, as it worked in 6.0.
We believe this is because of the change we did where we've started prefixing all the type names with `global::`: https://github.com/dotnet/razor-compiler/pull/34

I think this should be addressed in 7.0.

**Comment by jaredpar** [comment]
@333fred this is another variation on the `global::` problem we saw with tuples. Did your change fix this for `dynamic` as well? If not we should consider all the other type forms for which `global::` is not a valid prefix.

**Comment by 333fred** [comment]
@jjonescz, this is a fairly simple change similar to https://github.com/dotnet/razor-compiler/pull/340.

**Comment by Junjun-zhao** [comment]
@jjonescz We verified this issue on the latest RC2 build dotnet-sdk-7.0.100-rc.2.22466.28, it is still repo. Could you help check whether it has consumed the fix? Thanks.

```
.NET SDK:
Version:   7.0.100-rc.2.22466.28
Commit:    60fdbb471d

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.22000
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\7.0.100-rc.2.22466.28\

Host:
  Version:      7.0.0-rc.2.22464.1
  Architecture: x64
  Commit:       c623d96fe3

.NET SDKs installed:
  7.0.100-rc.2.22466.28 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-rc.2.22464.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22464.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.2.22459.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

**Comment by jaredpar** [comment]
@Junjun-zhao looks like code flow didn't happen correctly to the sdk. Looking into it.

**Comment by Junjun-zhao** [comment]
Verified and this issue has been fixed on latest RC2 build 7.0.100-rc.2.22477.23. Thanks
